services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
    - ./frontend/node_modules:/app/node_modules
  backend:
    build: ./
    ports:
      - "8080:8080"
    env_file:
      - .env